version: 2.1

commands:
    checkout_restore_cache:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "build.gradle" }}
                    - v1-dependencies-

executors:
    gradle: 
        docker:
            - image: circleci/openjdk:8-jdk
        
jobs:
    dependencies:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew dependencies
            - save_cache:
                paths:
                    - ~/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}
    core_test:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew core:test

workflows:
    version: 2.1
    integration:
        jobs:
            - dependencies
            - core_test:
                  requires:
                      - dependencies
