version: 2.1

commands:
    checkout_restore_gradle_cache:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "build.gradle" }}
                    - v1-dependencies-
    checkout_restore_node_cache:
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v2-dependencies-{{ checksum "package-lock.json" }}
                      - v2-dependencies-

executors:
    gradle: 
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            JVM_OPTS: -Xmx3200m
            TERM: dumb
    node:
        docker:
            - image: circleci/node:10.15.3
        working_directory: ~/panel
    node_browsers:
        docker:
            - image: circleci/node:10-browsers
        working_directory: ~/panel

jobs:
    # install
    install:
        executor: node
        steps:
            - checkout_restore_node_cache
            - run: npm install
            - save_cache:
                paths:
                    - ./node_modules
                key: v2-dependencies-{{ checksum "package-lock.json" }}
    dependencies:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew dependencies
            - save_cache:
                paths:
                    - ~/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}
    # tests
    core_test:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew core:test
    desktop_test:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew desktop:test
    mercenaire_test:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew mercenaire:test
    server_test:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew server:test
    panel_lint:
        executor: node
        steps:
            - checkout_restore_node_cache
            - run: npm run lint
    panel_test:
        executor: node_browsers
        steps:
            - checkout_restore_node_cache
            - run: npm run test:ci
    panel_e2e:
        executor: node_browsers
        steps:
            - checkout_restore_node_cache
            - run: npm run e2e:ci
    #builds
    desktop_build:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew dist
    server_build:
        executor: gradle
        steps:
            - checkout_restore_gradle_cache
            - run: ./gradlew build
    panel_build:
        executor: node
        steps:
            - checkout_restore_node_cache
            - run: npm run build

workflows:
    version: 2.1
    integration:
        jobs:
            - dependencies
            - install
            - panel_lint:
                requires:
                    - install
            - panel_test:
                requires:
                    - install
            - panel_e2e:
                requires:
                    - install
            - mercenaire_test:
                requires:
                    - dependencies
            - core_test:
                requires:
                    - dependencies
            - desktop_test:
                requires:
                    - dependencies
            - server_test:
                requires:
                    - dependencies
            - desktop_build:
                requires:
                    - desktop_test
            - server_build:
                requires:
                    - server_test
            - panel_build:
                requires:
                    - install
                    - desktop_build
                    - server_build
