version: 2.1

commands:
    checkout_restore_cache:
        steps:
            - checkout
            - restore_cache:
                keys:
                    - v1-dependencies-{{ checksum "build.gradle" }}
                    - v1-dependencies-

executors:
    gradle: 
        docker:
            - image: circleci/openjdk:8-jdk
        environment:
            JVM_OPTS: -Xmx3200m
            TERM: dumb

jobs:
    dependencies:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew dependencies
            - save_cache:
                paths:
                    - ~/.gradle
                key: v1-dependencies-{{ checksum "build.gradle" }}
    core_test:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew core:test
    desktop_test:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew desktop:test
    mercenaire_test:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew mercenaire:test
    server_test:
        executor: gradle
        steps:
            - checkout_restore_cache
            - run: ./gradlew server:test

workflows:
    version: 2.1
    integration:
        jobs:
            - dependencies
            - mercenaire_test:
                  requires:
                      - dependencies
            - core_test:
                  requires:
                      - dependencies
            - desktop_test:
                  requires:
                      - dependencies
            - server_test:
                  requires:
                      - dependencies
